import "fastify";
import type Database from "better-sqlite3";
import type { ProjectRepository } from "../db/repositories/project.js";
import type { SessionRepository } from "../db/repositories/session.js";
import type { MessageRepository } from "../db/repositories/message.js";
import type { ModelRepository } from "../db/repositories/model.js";
import type { ProcessManager } from "../agent/process-manager.js";
import type { SessionStateStore } from "../agent/session-state.js";
import type { SessionEventBuffer } from "../agent/session-event-buffer.js";
import type { SkillService } from "../agent/skill-service.js";
import type { SkillStoreService } from "../skill-store/skill-store-service.js";
import type { KnowledgeBaseRepository } from "../db/repositories/knowledge-base.js";
import type { KbFileRepository } from "../db/repositories/kb-file.js";
import type { KbChunkRepository } from "../db/repositories/kb-chunk.js";
import type { SessionKbBindingRepository } from "../db/repositories/session-kb-binding.js";
import type { KbSearchService } from "../kb/search-service.js";
import type { KbParseJobRepository } from "../db/repositories/kb-parse-job.js";
import type { KbParseJobWorker } from "../kb/parse-job-worker.js";
import type { ExpertRepository } from "../db/repositories/expert.js";
import type { ScheduledTaskRepository, TaskLogRepository } from "../db/repositories/scheduled-task.js";
import type { TaskScheduler } from "../services/task-scheduler.js";
import type { ChannelRepository } from "../db/repositories/channel.js";
import type { ChannelConversationRepository } from "../db/repositories/channel-conversation.js";
import type { Config } from "../config.js";
import type { BrowserSessionManager } from "../browser/browser-session-manager.js";
import type { ComputerSessionManager } from "../computer/computer-session-manager.js";
import type { PluginRepository } from "../db/repositories/plugin.js";
import type { PluginManager } from "../plugins/plugin-manager.js";
import type { PluginPermissionService } from "../plugins/plugin-permission-service.js";

declare module "fastify" {
  interface FastifyInstance {
    db: Database.Database;
    projects: ProjectRepository;
    sessions: SessionRepository;
    messages: MessageRepository;
    models: ModelRepository;
    processManager: ProcessManager;
    sessionStates: SessionStateStore;
    sessionEvents: SessionEventBuffer;
    skills: SkillService;
    skillStore: SkillStoreService;
    knowledgeBases: KnowledgeBaseRepository;
    kbFiles: KbFileRepository;
    kbChunks: KbChunkRepository;
    kbBindings: SessionKbBindingRepository;
    kbSearch: KbSearchService;
    kbParseJobs: KbParseJobRepository;
    kbParseWorker: KbParseJobWorker;
    experts: ExpertRepository;
    scheduledTasks: ScheduledTaskRepository;
    taskLogs: TaskLogRepository;
    taskScheduler: TaskScheduler;
    channels: ChannelRepository;
    channelConversations: ChannelConversationRepository;
    config: Config;
    browserManager: BrowserSessionManager;
    computerManager: ComputerSessionManager;
    plugins: PluginRepository;
    pluginManager: PluginManager;
    pluginPermissions: PluginPermissionService;
  }
}
